### ISSUE TITLE
`getTasklistToken` leaves a handle open

### ISSUE THREAD

**Issue by pepopowitz** [camunda-community-hub/camunda-saas-oauth-nodejs#21]
When calling `getTasklistToken`, a handle is left open. 

Example: 

[This test](https://github.com/camunda-community-hub/tasklist-client-node-js/blob/d01d6e28595ef8e960cc6be03358131d1df6ddc9/src/__test__/test.spec.ts#L44-L48) calls `getTasklistToken` [under the covers](https://github.com/camunda-community-hub/tasklist-client-node-js/blob/d01d6e28595ef8e960cc6be03358131d1df6ddc9/src/lib/TasklistApiClient.ts#L52-L59). When running the test locally, Jest gives an error about the handle left open by `getTasklistToken`: 

<img width="907" alt="image" src="https://github.com/camunda-community-hub/camunda-saas-oauth-nodejs/assets/1627089/0ea2909c-93ec-4c03-8815-b503973b7799">

The above output as text, in case that's useful:

```
❯ npm run test

> camunda-tasklist-client@0.9.5 test
> jest --detectOpenHandles --runInBand --forceExit

 PASS  src/__test__/test.spec.ts (14.538 s)
  TasklistApiClient
    ✓ can request all tasks (12021 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        14.673 s
Ran all test suites.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      65 |
      66 |   private async getHeaders() {
    > 67 |     const token = await getTasklistToken(this.userAgentString);
         |                                         ^
      68 |     return {
      69 |       'content-type': 'application/json',
      70 |       authorization: `Bearer ${token}`,

      at OAuthProviderImpl.startExpiryTimer (node_modules/camunda-saas-oauth/dist/lib/OAuthProviderImpl.js:195:28)
      at OAuthProviderImpl.fromFileCache (node_modules/camunda-saas-oauth/dist/lib/OAuthProviderImpl.js:160:18)
      at OAuthProviderImpl.<anonymous> (node_modules/camunda-saas-oauth/dist/lib/OAuthProviderImpl.js:88:42)
      at node_modules/camunda-saas-oauth/dist/lib/OAuthProviderImpl.js:31:71
      at Object.<anonymous>.__awaiter (node_modules/camunda-saas-oauth/dist/lib/OAuthProviderImpl.js:27:12)
      at OAuthProviderImpl.getToken (node_modules/camunda-saas-oauth/dist/lib/OAuthProviderImpl.js:82:16)
      at getTasklistToken (node_modules/camunda-saas-oauth/dist/lib/Tasklist.js:18:34)
```

## Details 

As discussed in person with @jwulf, the cause of the open handle is the starting of a timeout so that the token can be evicted from the cache after it expires. To fix this open handle, it might make sense to evict tokens from the cache upon request, if they've exceeded their expiration, instead of using a timer.

**Comment by jwulf** [comment]
This is fixed in the new client: https://github.com/camunda-community-hub/camunda-8-js-sdk
