### ISSUE TITLE
support credentials via constructor

### ISSUE THREAD

**Issue by nhomble** [camunda-community-hub/camunda-saas-oauth-nodejs#5]
Pulling credentials from environment as a default is very reasonable. The node zeebe client will do the same with its zero-configuration constructor. As a fallback, it would make the library a lot more flexible if it could take in (optionally) constructor arguments. This would be similar to how the [zeebe-node](https://github.com/camunda-community-hub/zeebe-client-node-js) library does it.

**Comment by nhomble** [comment]
This is becoming an issue and less of a quality-of-life ticket. Because the constructor **always* gets the creds from env with the cache flag defaulted to true

https://github.com/camunda-community-hub/camunda-saas-oauth-nodejs/blob/main/src/lib/Operate.ts#L8

This means that in a runtime where we want to access multiple clusters, this client is unusable.

**Comment by jwulf** [comment]
Ah, `OAuthProvider` is a wrapper for `OAuthProviderImpl`. Credentials from the environment are injected in that wrapper. So you can use `OAuthProviderImpl` directly, like this:

```typescript
import { OAuthProviderImpl } from 'camunda-saas-oauth'

const oauth = new OAuthProviderImpl({
        /** OAuth Endpoint URL */
        authServerUrl,
        /** OAuth Audience */
        audience, clientId, clientSecret,
        userAgentString
})

oauth.getToken('OPERATE')
oauth.getToken('OPTIMIZE')
oauth.getToken('TASKLIST')
oauth.getToken('ZEEBE')
```

**Comment by nhomble** [comment]
Gotcha, and then one step further (sorry this is cross-repo), could https://github.com/camunda-community-hub/operate-client-node-js/blob/main/src/lib/OperateApiClient.ts#L36 take in this provider?

**Comment by jwulf** [comment]
Yes, I have a strategy in mind for this.

**Comment by jwulf** [comment]
Done.

**Comment by jwulf** [comment]
Done.
